load("@bazel_gazelle//:def.bzl", "gazelle")
load("@bazeldnf//bazeldnf:defs.bzl", "bazeldnf")
load("@buildifier_prebuilt//:rules.bzl", "buildifier")
load("@com_github_ash2k_bazel_tools//goimports:def.bzl", "goimports")
load("@io_bazel_rules_go//go:def.bzl", "go_library", "nogo")
load("@rules_distroless//distroless:defs.bzl", "passwd")
load("@rules_pkg//:pkg.bzl", "pkg_tar")
load("@rules_shell//shell:sh_binary.bzl", "sh_binary")

passwd(
    name = "passwd",
    entries = [
        dict(
            gecos = ["nonroot-user"],
            gid = 1001,
            home = "/home/nonroot-user",
            shell = "/usr/bin/bash",
            uid = 1001,
            username = "nonroot-user",
        ),
        dict(
            gecos = ["root"],
            gid = 0,
            home = "/root",
            shell = "/usr/bin/bash",
            uid = 0,
            username = "root",
        ),
    ],
)

pkg_tar(
    name = "passwd-tar",
    srcs = [":passwd"],
    mode = "0644",
    package_dir = "etc",
    visibility = ["//visibility:public"],
)

goimports(
    name = "goimports",
    display_diffs = True,
    exclude_paths = [
        "./vendor/*",
        "./.history/*",
        "./.git/*",
        "./_ci-configs/*",
    ],
    local = ["kubevirt.io/kubevirt"],
    prefix = "kubevirt.io/kubevirt",
    write = True,
)

nogo(
    name = "nogo_vet",
    config = "nogo_config.json",
    visibility = ["//visibility:public"],
    # These deps enable the analyses equivalent to running `go vet`.
    # Passing vet = True enables only a tiny subset of these (the ones
    # that are always correct).
    # You can see the what `go vet` does by running `go doc cmd/vet`.
    deps = [
        # Nogo dependencies removed due to issue with gazelle recreating the
        # Build.bazel files
        #"//vendor/github.com/nunnatsa/ginkgolinter:go_default_library",
        "//tools/analyzers/banncheck:go_default_library",
        #"//vendor/github.com/gordonklaus/ineffassign/pkg/ineffassign:go_default_library",
        #"//vendor/github.com/kisielk/errcheck/errcheck:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/asmdecl:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/assign:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/atomic:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/bools:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/buildtag:go_default_library",
        # Fails on a vendored dependency, disabling for now.
        # "@org_golang_x_tools//go/analysis/passes/cgocall:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/composite:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/copylock:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/httpresponse:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/loopclosure:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/lostcancel:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/nilfunc:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/printf:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/shift:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/stdmethods:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/structtag:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/tests:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/unreachable:go_default_library",
        # FIXME: Nogo fails analysis although configured to be disabled on nogo_config.json.
        # "@org_golang_x_tools//go/analysis/passes/unsafeptr:go_default_library",
        "@org_golang_x_tools//go/analysis/passes/unusedresult:go_default_library",
    ],
)

# gazelle:prefix kubevirt.io/kubevirt
# gazelle:build_tags selinux
# gazelle:proto disable_global
# gazelle:resolve go golang.org/x/tools/go/analysis @org_golang_x_tools//go/analysis:go_default_library
gazelle(
    name = "gazelle",
    build_tags = ["selinux"],
)

bazeldnf(name = "bazeldnf")

alias(
    name = "buildozer",
    actual = "@buildifier_prebuilt//:buildozer",
)

buildifier(
    name = "buildifier",
)

genrule(
    name = "get-version",
    srcs = [],
    outs = [".version"],
    cmd = "grep ^STABLE_BUILD_SCM_REVISION bazel-out/stable-status.txt | cut -d' ' -f2 >$@",
    stamp = 1,
    visibility = ["//visibility:public"],
)

cc_library(
    name = "libvirt-libs",
    srcs = ["//bazel/compat:libvirt-libs-lib"],
    hdrs = ["//bazel/compat:libvirt-libs-headers"],
    linkstatic = 1,
    strip_include_prefix = select({
        "@io_bazel_rules_go//go/platform:linux_amd64": "/rpm/libvirt-libs_x86_64/usr/include",
        "@io_bazel_rules_go//go/platform:linux_arm64": "/rpm/libvirt-libs_aarch64/usr/include/",
        "@io_bazel_rules_go//go/platform:linux_s390x": "/rpm/libvirt-libs_s390x/usr/include/",
        "//conditions:default": "/rpm/libvirt-libs_x86_64/usr/include/",
    }),
    visibility = ["//visibility:public"],
)

config_setting(
    name = "release",
    values = {"define": "release=true"},
)

# Aliases for oci_push targets - the actual rules are defined alongside the images
alias(
    name = "push-virt-operator",
    actual = "//cmd/virt-operator:push",
)

alias(
    name = "push-virt-api",
    actual = "//cmd/virt-api:push",
)

alias(
    name = "push-virt-controller",
    actual = "//cmd/virt-controller:push",
)

alias(
    name = "push-virt-handler",
    actual = "//cmd/virt-handler:push",
)

alias(
    name = "push-virt-launcher",
    actual = "//cmd/virt-launcher:push",
)

alias(
    name = "push-conformance",
    actual = "//tests:push",
)

alias(
    name = "push-libguestfs-tools",
    actual = "//cmd/libguestfs:push",
)

alias(
    name = "push-virt-exportserver",
    actual = "//cmd/virt-exportserver:push",
)

alias(
    name = "push-virt-exportproxy",
    actual = "//cmd/virt-exportproxy:push",
)

alias(
    name = "push-virt-synchronization-controller",
    actual = "//cmd/synchronization-controller:push",
)

alias(
    name = "push-pr-helper",
    actual = "//cmd/pr-helper:push",
)

alias(
    name = "push-sidecar-shim",
    actual = "//cmd/sidecars:push",
)

alias(
    name = "push-network-slirp-binding",
    actual = "//cmd/sidecars/network-slirp-binding:push",
)

alias(
    name = "push-network-passt-binding",
    actual = "//cmd/sidecars/network-passt-binding:push",
)

alias(
    name = "push-network-passt-binding-cni",
    actual = "//cmd/cniplugins/passt-binding/cmd:push",
)

alias(
    name = "push-example-hook-sidecar",
    actual = "//cmd/sidecars/smbios:push",
)

alias(
    name = "push-example-disk-mutation-hook-sidecar",
    actual = "//cmd/sidecars/disk-mutation:push",
)

alias(
    name = "push-example-cloudinit-hook-sidecar",
    actual = "//cmd/sidecars/cloudinit:push",
)

alias(
    name = "push-alpine-container-disk-image",
    actual = "//containerimages:push-alpine-container-disk-image",
)

alias(
    name = "push-cirros-container-disk-image",
    actual = "//containerimages:push-cirros-container-disk-image",
)

alias(
    name = "push-cirros-custom-container-disk-image",
    actual = "//containerimages:push-cirros-custom-container-disk-image",
)

alias(
    name = "push-virtio-container-disk-image",
    actual = "//containerimages:push-virtio-container-disk-image",
)

alias(
    name = "push-alpine-ext-kernel-boot-demo-image",
    actual = "//containerimages:push-alpine-ext-kernel-boot-demo-image",
)

alias(
    name = "push-fedora-with-test-tooling-image",
    actual = "//containerimages:push-fedora-with-test-tooling-image",
)

alias(
    name = "push-alpine-with-test-tooling-image",
    actual = "//containerimages:push-alpine-with-test-tooling-image",
)

alias(
    name = "push-fedora-realtime-image",
    actual = "//containerimages:push-fedora-realtime-image",
)

alias(
    name = "push-disks-images-provider",
    actual = "//images/disks-images-provider:push",
)

alias(
    name = "push-vm-killer",
    actual = "//images/vm-killer:push",
)

alias(
    name = "push-winrmcli",
    actual = "//images/winrmcli:push",
)

genrule(
    name = "build-virtctl",
    srcs = [
        "//cmd/virtctl",
    ],
    outs = ["virtctl-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-virtctl-amd64",
    srcs = [
        "//cmd/virtctl:virtctl-amd64",
    ],
    outs = ["virtctl-copier-amd64"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-virtctl-darwin",
    srcs = [
        "//cmd/virtctl:virtctl-darwin",
    ],
    outs = ["virtctl-copier-darwin"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-virtctl-windows",
    srcs = [
        "//cmd/virtctl:virtctl-windows",
    ],
    outs = ["virtctl-copier-windows"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-virtctl-arm64",
    srcs = [
        "//cmd/virtctl:virtctl-arm64",
    ],
    outs = ["virtctl-copier-arm64"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-virtctl-darwin-arm64",
    srcs = [
        "//cmd/virtctl:virtctl-darwin-arm64",
    ],
    outs = ["virtctl-copier-darwin-arm64"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-virtctl-s390x",
    srcs = [
        "//cmd/virtctl:virtctl-s390x",
    ],
    outs = ["virtctl-copier-s390x"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-ginkgo",
    srcs = [
        "//vendor/github.com/onsi/ginkgo/v2/ginkgo",
    ],
    outs = ["ginkgo-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-manifest-templator",
    srcs = [
        "//tools/manifest-templator:templator",
    ],
    outs = ["manifest-templator-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-perfscale-audit",
    srcs = [
        "//tools/perfscale-audit",
    ],
    outs = ["perfscale-audit-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-perfscale-load-generator",
    srcs = [
        "//tools/perfscale-load-generator",
    ],
    outs = ["perfscale-load-generator-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-cluster-profiler",
    srcs = [
        "//tools/cluster-profiler",
    ],
    outs = ["cluster-profiler-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-junit-merger",
    srcs = [
        "//tools/junit-merger",
    ],
    outs = ["junit-merger-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-functests",
    testonly = True,
    srcs = [
        "//tests:go_default_test",
    ],
    outs = ["functests-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-example-guest-agent",
    testonly = True,
    srcs = [
        "//cmd/example-guest-agent",
    ],
    outs = ["example-guest-agent-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

genrule(
    name = "build-dump",
    srcs = [
        "//cmd/dump",
    ],
    outs = ["dump-copier"],
    cmd = "echo '#!/bin/sh\n\ncp -f $(SRCS) $$1' > \"$@\"",
    executable = 1,
)

filegroup(
    name = "coverage_files",
    srcs = glob(["bazel-out/k8-fastbuild/testlogs/**/coverage.dat"]),
)

genrule(
    name = "goveralls",
    srcs = [
        ":coverage_files",
    ],
    outs = ["bazel-goveralls"],
    cmd = "echo '#!/bin/sh\n\necho $(SRCS) | hack/goveralls.sh'  > \"$@\"",
    executable = 1,
)

genrule(
    name = "coverage-report",
    srcs = [
        ":coverage_files",
    ],
    outs = ["bazel-coverage-report"],
    cmd = "echo '#!/bin/sh\n\necho $(SRCS) | hack/coverage-report.sh'  > \"$@\"",
    executable = 1,
)

go_library(
    name = "go_default_library",
    srcs = ["doc.go"],
    importpath = "kubevirt.io/kubevirt",
    visibility = ["//visibility:public"],
)
