load("@bazel_gazelle//:def.bzl", "gazelle")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

gazelle(name = "gazelle")

pkg_tar(
    name = "winrm-cli-tar",
    srcs = [
        "@com_github_masterzen_winrm_cli//:winrm-cli",
        "@com_github_packer_community_winrmcp//:winrmcp",
    ],
    package_dir = "/usr/bin",
)

oci_image(
    name = "winrmcli-image",
    base = "//images:kubevirt-testing-base",
    tars = [
        ":winrm-cli-tar",
    ],
)

oci_push(
    name = "push",
    image = ":winrmcli-image",
    repository = "quay.io/kubevirt/winrmcli",
    visibility = ["//visibility:public"],
)

oci_load(
    name = "load",
    image = ":winrmcli-image",
    repo_tags = ["bazel/winrmcli:latest"],
)
