load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "multipath",
    srcs = [":multipath.conf"],
    mode = "0600",
    package_dir = "/etc",
)

pkg_tar(
    name = "get-version",
    srcs = ["//:get-version"],
    package_dir = "/",
)

pkg_tar(
    name = "entrypoint",
    srcs = [":entrypoint.sh"],
    mode = "0700",
    package_dir = "/",
)

oci_image(
    name = "pr-helper-image",
    base = "//bazel/compat:go_image_base",
    tars = [
        "//bazel/compat:pr-helper",
        "//:passwd-tar",
        ":multipath",
        ":entrypoint",
        ":get-version",
    ],
    user = "1001",
    entrypoint = ["/usr/bin/qemu-pr-helper"],
)

oci_push(
    name = "push",
    image = ":pr-helper-image",
    repository = "quay.io/kubevirt/pr-helper",
    visibility = ["//visibility:public"],
)

oci_load(
    name = "load",
    image = ":pr-helper-image",
    repo_tags = ["bazel/pr-helper:latest"],
)
