load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

pkg_tar(
    name = "alpine-image-tar",
    srcs = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": ["@alpine_image_aarch64//file"],
        "@io_bazel_rules_go//go/platform:linux_s390x": ["@alpine_image_s390x//file"],
        "//conditions:default": ["@alpine_image//file"],
    }),
    extension = "tar.gz",
    mode = "440",
    owner = "107.107",
    package_dir = "/disk",
)

oci_image(
    name = "alpine-container-disk-image",
    architecture = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": "arm64",
        "@io_bazel_rules_go//go/platform:linux_s390x": "s390x",
        "//conditions:default": "amd64",
    }),
    os = "linux",
    tars = [":alpine-image-tar"],
)

pkg_tar(
    name = "cirros-image-tar",
    srcs = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": ["@cirros_image_aarch64//file"],
        "//conditions:default": ["@cirros_image//file"],
    }),
    mode = "440",
    owner = "107.107",
    package_dir = "/disk",
)

oci_image(
    name = "cirros-container-disk-image",
    architecture = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": "arm64",
        "//conditions:default": "amd64",
    }),
    os = "linux",
    tars = [":cirros-image-tar"],
)

pkg_tar(
    name = "cirros-custom-image-tar",
    srcs = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": ["@cirros_image_aarch64//file"],
        "//conditions:default": ["@cirros_image//file"],
    }),
    mode = "440",
    owner = "107.107",
    package_dir = "/custom-disk",
)

# used for e2e testing of custom base baths
oci_image(
    name = "cirros-custom-container-disk-image",
    architecture = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": "arm64",
        "//conditions:default": "amd64",
    }),
    os = "linux",
    tars = [":cirros-custom-image-tar"],
)

pkg_tar(
    name = "virtio-image-tar",
    srcs = ["@virtio_win_image//file"],
    mode = "440",
    owner = "107.107",
    package_dir = "/disk",
)

oci_image(
    name = "virtio-container-disk-image",
    architecture = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": "arm64",
        "//conditions:default": "amd64",
    }),
    os = "linux",
    tars = [":virtio-image-tar"],
)

oci_image(
    name = "fedora-with-test-tooling",
    base = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": "@fedora_with_test_tooling_aarch64",
        "@io_bazel_rules_go//go/platform:linux_s390x": "@fedora_with_test_tooling_s390x",
        "//conditions:default": "@fedora_with_test_tooling",
    }),
)

oci_image(
    name = "alpine-with-test-tooling",
    base = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": "@alpine_with_test_tooling",
        "@io_bazel_rules_go//go/platform:linux_s390x": "@alpine_with_test_tooling",
        "//conditions:default": "@alpine_with_test_tooling",
    }),
)

oci_image(
    name = "alpine-ext-kernel-boot-demo-container",
    base = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": "@alpine-ext-kernel-boot-demo-container-base",
        "@io_bazel_rules_go//go/platform:linux_s390x": "@alpine-ext-kernel-boot-demo-container-base",
        "//conditions:default": "@alpine-ext-kernel-boot-demo-container-base",
    }),
    tars = [":alpine-image-tar"],
)

oci_image(
    name = "fedora-realtime",
    base = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": "@fedora_realtime",
        "@io_bazel_rules_go//go/platform:linux_s390x": "@fedora_realtime",
        "//conditions:default": "@fedora_realtime",
    }),
)

oci_push(
    name = "push-alpine-container-disk-image",
    image = ":alpine-container-disk-image",
    repository = "quay.io/kubevirt/alpine-container-disk-demo",
    visibility = ["//visibility:public"],
)

oci_push(
    name = "push-cirros-container-disk-image",
    image = ":cirros-container-disk-image",
    repository = "quay.io/kubevirt/cirros-container-disk-demo",
    visibility = ["//visibility:public"],
)

oci_push(
    name = "push-cirros-custom-container-disk-image",
    image = ":cirros-custom-container-disk-image",
    repository = "quay.io/kubevirt/cirros-custom-container-disk-demo",
    visibility = ["//visibility:public"],
)

oci_push(
    name = "push-virtio-container-disk-image",
    image = ":virtio-container-disk-image",
    repository = "quay.io/kubevirt/virtio-container-disk",
    visibility = ["//visibility:public"],
)

oci_push(
    name = "push-alpine-ext-kernel-boot-demo-image",
    image = ":alpine-ext-kernel-boot-demo-container",
    repository = "quay.io/kubevirt/alpine-ext-kernel-boot-demo",
    visibility = ["//visibility:public"],
)

oci_push(
    name = "push-fedora-with-test-tooling-image",
    image = ":fedora-with-test-tooling",
    repository = "quay.io/fedora-with-test-tooling-container-disk",
    visibility = ["//visibility:public"],
)

oci_push(
    name = "push-alpine-with-test-tooling-image",
    image = ":alpine-with-test-tooling",
    repository = "quay.io/kubevirt/alpine-with-test-tooling-container-disk",
    visibility = ["//visibility:public"],
)

oci_push(
    name = "push-fedora-realtime-image",
    image = ":fedora-realtime",
    repository = "quay.io/kubevirt/fedora-realtime-container-disk",
    visibility = ["//visibility:public"],
)

oci_load(
    name = "load-alpine-container-disk-image",
    image = ":alpine-container-disk-image",
    repo_tags = ["bazel/alpine-container-disk:latest"],
)

oci_load(
    name = "load-cirros-container-disk-image",
    image = ":cirros-container-disk-image",
    repo_tags = ["bazel/cirros-container-disk:latest"],
)

oci_load(
    name = "load-cirros-custom-container-disk-image",
    image = ":cirros-custom-container-disk-image",
    repo_tags = ["bazel/cirros-custom-container-disk:latest"],
)

oci_load(
    name = "load-virtio-container-disk-image",
    image = ":virtio-container-disk-image",
    repo_tags = ["bazel/virtio-container-disk:latest"],
)

oci_load(
    name = "load-alpine-ext-kernel-boot-demo",
    image = ":alpine-ext-kernel-boot-demo-container",
    repo_tags = ["bazel/alpine-ext-kernel-boot-demo-container:latest"],
)

oci_load(
    name = "load-fedora-with-test-tooling",
    image = ":fedora-with-test-tooling",
    repo_tags = ["bazel/fedora-with-test-tooling:latest"],
)

oci_load(
    name = "load-alpine-with-test-tooling",
    image = ":alpine-with-test-tooling",
    repo_tags = ["bazel/alpine-with-test-tooling:latest"],
)

oci_load(
    name = "load-fedora-realtime",
    image = ":fedora-realtime",
    repo_tags = ["bazel/fedora-realtime:latest"],
)
