load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@rules_oci//oci:defs.bzl", "oci_image", "oci_load", "oci_push")
load("@rules_pkg//:pkg.bzl", "pkg_tar")

go_library(
    name = "go_default_library",
    srcs = ["main.go"],
    importpath = "kubevirt.io/kubevirt/cmd/sidecars/network-slirp-binding",
    visibility = ["//visibility:private"],
    deps = [
        "//cmd/sidecars/network-slirp-binding/dns:go_default_library",
        "//cmd/sidecars/network-slirp-binding/server:go_default_library",
        "//pkg/hooks:go_default_library",
        "//pkg/hooks/info:go_default_library",
        "//pkg/hooks/v1alpha2:go_default_library",
        "//staging/src/kubevirt.io/client-go/log:go_default_library",
        "//vendor/google.golang.org/grpc:go_default_library",
    ],
)

go_binary(
    name = "network-slirp-binding",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

pkg_tar(
    name = "get-version",
    srcs = ["//:get-version"],
    package_dir = "/",
)

pkg_tar(
    name = "network-slirp-binding-tar",
    srcs = [":network-slirp-binding"],
    package_dir = "/",
)

oci_image(
    name = "network-slirp-binding-image",
    base = "//bazel/compat:go_image_base",
    entrypoint = ["/network-slirp-binding"],
    tars = [
        "//:passwd-tar",
        ":network-slirp-binding-tar",
        ":get-version",
    ],
    user = "1001",
)

oci_push(
    name = "push",
    image = ":network-slirp-binding-image",
    repository = "quay.io/kubevirt/network-slirp-binding",
    visibility = ["//visibility:public"],
)

oci_load(
    name = "load",
    image = ":network-slirp-binding-image",
    repo_tags = ["bazel/network-slirp-binding:latest"],
)
