load("@rules_distroless//distroless:defs.bzl", "group", "passwd")
load("@rules_oci//oci:defs.bzl", "oci_image")
load("//bazel:image.bzl", "provision_user")

oci_image(
    name = "kubevirt-testing-base",
    architecture = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": "arm64",
        "@io_bazel_rules_go//go/platform:linux_s390x": "s390x",
        "//conditions:default": "amd64",
    }),
    os = "linux",
    tars = select({
        "@io_bazel_rules_go//go/platform:linux_arm64": [
            "//rpm:testimage_aarch64",
            ":passwd",
            ":group",
        ],
        "@io_bazel_rules_go//go/platform:linux_s390x": [
            "//rpm:testimage_s390x",
            ":passwd",
            ":group",
        ],
        "//conditions:default": [
            "//rpm:testimage_x86_64",
            ":user-layer",
        ],
    }),
    visibility = ["//visibility:public"],
)

provision_user(
    name = "user-layer",
    gid = 101,
    groupname = "nginx",
    uid = 101,
    username = "nginx",
)
